---
kubernetes_version: "v1.32.6"
kubernetes_package_version: "1.32.6-1.1"
loadbalancer_apiserver: ctrp.infra-hetzner.glueops.onglueops.com
haproxy_listen_port: 6443

etcd_version: "3.5.11"
etcd_data_dir: "/var/lib/etcd"
etcd_peer_port: 2380
etcd_client_port: 2379

lb_nodes:
  - worker-node-0
  - worker-node-1
  - worker-node-3
  - worker-node-4
