
- name: Copy taint-label python script
  ansible.builtin.copy:
    src: "taint-label-nodes.py"
    dest: "/opt/kubernetes/taint-label-nodes.py"
    mode: "0644"
  tags: label_nodes


- name: taint and label Nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    export DATA="{{ item }}"
    python3 /opt/kubernetes/taint-label-nodes.py
  with_items: "{{ values }}"
  tags: label_nodes
